### ISSUE TITLE
Content-Type for Response should be multipart/mixed

### ISSUE THREAD

**Issue by prigazzi** [wouterlemcke/http-multipart-response-handler#1]
We're currently using multipart/form-data, but that's a format for formating Multipart Requests that include Form data in a different setting that the default body. 
Another problem of multipart/form-data is that limits the number and type of Headers we can add to the different multiparts.

More info: 
https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by prigazzi** [comment]
The Content-Type should also include the "boundary" string being used to be able to properly break the messages on the receiving end.

**Comment by wouterlemcke** [comment]
Fixed in #6
